AWS_ACCESS_KEY_ID: "AKIAJXBUBUZMWXZYJOJQ"
AWS_SECRET_ACCESS_KEY: "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"
APP_SECRET: "mmsx0axvi71pl4n"
ACCESS_TOKEN_SECRET: "7y77irpaitjihdx"
STRIPE_API_KEY: "sk_test_r5On0TMzqzxYHAuMei1O9JiO"
STRIPE_PUBLIC_KEY: "pk_test_gMxItqRx55o69A4ZC8uf7nXH"
SECRET_KEY_BASE: "1d064cb87773055138cbb5747a3a76808f6c4e043daf085b490f8f1befb4edd6c3dccf66c90ade102b58200694486aa1cab6363d279cbb07b76f896f196e96d8"